### ISSUE TITLE
'npm start' failed

### ISSUE THREAD

**Issue by tipoc123** [nedap/exonum-block-explorer#1]
```
root@horizontalvol:~/exonum/exonum-block-explorer# npm start

> exonum-block-explorer@0.0.1 start /root/exonum/exonum-block-explorer
> webpack-dev-server

/root/exonum/exonum-block-explorer/webpack.config.js:6
let cleanOptions = {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/root/exonum/exonum-block-explorer/node_modules/webpack/bin/convert-argv.js:96:18)
    at /root/exonum/exonum-block-explorer/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! exonum-block-explorer@0.0.1 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the exonum-block-explorer@0.0.1 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the exonum-block-explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs exonum-block-explorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls exonum-block-explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/exonum/exonum-block-explorer/npm-debug.log

```

**Comment by tipoc123** [comment]
I use exonum 0.4.0

**Comment by tipoc123** [comment]
[npm-debug.log](https://github.com/nedap/exonum-block-explorer/files/1585086/npm-debug.log)

**Comment by tipoc123** [comment]
I have fixed this by adding "use strict" to the beginning of webpack.config.js file.

**Comment by vnermolaev** [comment]
According to your log, you use very outdated node and npm (node@v4.2.66, npm@3.5.2) while the current versions at the time of writing are  node@8.9.3 and npm@5.5.1. I'd recommend to update the toolchain.
